# Site
name: "NFTs"
title: "A NFT Collective"
description: "The Next Big NFT Collective"
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: /NFTs
disqus: 'the-nft-collective'
mailchimp-list: 'https://etherstone.us1.list-manage.com/subscribe/post?u=e9f19d46d2992e2f66c22ce6b&amp;id=cd7af70c81'
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  Andrew:
    name: Andrew
    display_name: Andrew
    avatar: 'assets/images/avatar.jpg'
    web: https://www.digitalcpr.net
    twitter: https://twitter.com/gamer456148
    description: "I am a creator who is passionate about the things I write about"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
# adsense-data-ad-client: "ca-pub-3412143450191416"
# adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
